//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.20 at 08:04:53 AM UTC 
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import com.sei.generate.ClientTO;
import com.sei.generate.DeleteClientByIdRequest;
import com.sei.generate.DeleteClientByIdResponse;
import com.sei.generate.FetchClientByIdRequest;
import com.sei.generate.FetchClientByIdResponse;
import com.sei.generate.FetchClientsRequest;
import com.sei.generate.FetchClientsResponse;
import com.sei.generate.GetInfoRequest;
import com.sei.generate.GetInfoResponse;
import com.sei.generate.ObjectFactory;
import com.sei.generate.SaveClientRequest;
import com.sei.generate.SaveClientResponse;
import com.sei.generate.TransferObject;

public class JAXBDebug {


    public static JAXBContext createContext(ClassLoader classLoader)
        throws JAXBException
    {
        return JAXBContext.newInstance(FetchClientsRequest.class, FetchClientsResponse.class, ClientTO.class, FetchClientByIdRequest.class, FetchClientByIdResponse.class, SaveClientRequest.class, SaveClientResponse.class, DeleteClientByIdRequest.class, DeleteClientByIdResponse.class, TransferObject.class, GetInfoRequest.class, GetInfoResponse.class, ObjectFactory.class);
    }

}
